# Regenerate tests/testthat/fixtures/icensor-objective-oracle.csv (#543).
#
# A translated ICENSOR job is fitted with objective = "sas". This grid records
# what PROC HAZARD prints for optimised ICENSOR fits, so the test can compare
# the translated fit with it. The grid varies the PARMS model, the share of
# interval-censored rows and the interval width. Run from the package root:
#
#   Rscript data-raw/icensor-objective-oracle.R [path/to/hazard]
#
# The data are the package's own `avc`, written as the XPORT file the binary
# reads from $TMPDIR/hzr.<JOBID>.<JOBIX>.dta (hazard.sas, opnfils.c). C3 marks
# every `every`-th right-censored row as interval-censored, and TL is its
# lower bound, TT * (1 - width). A job for which the binary prints no
# log-likelihood is recorded with NA, never dropped, so the test can count
# every row.

args <- commandArgs(TRUE)
bin <- if (length(args)) args[[1L]] else
  path.expand("~/Documents/GitHub/hazard/dist/bin/hazard")
stopifnot(file.exists(bin), file.exists("data/avc.rda"))
work <- tempfile("icensor-objective-oracle-")
dir.create(work)

env <- new.env()
load("data/avc.rda", envir = env)
a <- env$avc[stats::complete.cases(env$avc), ]

parms <- c(
  "PARMS MUC=0.01; CONSTANT AGE;",
  "PARMS MUC=0.01;",
  "PARMS MUE=0.3 THALF=0.5 NU=1 M=1 MUC=0.005 FIXNU FIXM; EARLY AGE;",
  "PARMS MUE=0.3 THALF=0.5 NU=1 M=1 MUC=0.005 FIXTHALF FIXNU FIXM;"
)
grid <- expand.grid(model = seq_along(parms), every = c(5, 3),
                    width = c(0.5, 0.2, 0.9), degenerate = "none",
                    weighted = FALSE, stringsAsFactors = FALSE)
# Degenerate interval bounds, which readct.c resolves before the fit: on an
# ICENSOR row (C3 > 0) a missing, negative or greater-than-TIME CTIME deletes
# the row (readct.c:9-17), and CTIME == TIME makes it an exact event with
# C1 = C1 + C3 (readct.c:18-23). Each case edits the first three interval
# rows, alone and mixed, with and without WEIGHT.
grid <- rbind(grid, expand.grid(
  model = c(1L, 3L), every = 5, width = 0.5,
  degenerate = c("eq", "gt", "na", "neg", "mixed"), weighted = c(FALSE, TRUE),
  stringsAsFactors = FALSE))

degenerate_rows <- function(D, how) {
  i <- which(D$C3 > 0)[1:3]
  switch(how,
    none = D,
    eq = { D$TL[i] <- D$TT[i]; D },
    gt = { D$TL[i] <- D$TT[i] * 1.5; D },
    na = { D$TL[i] <- NA; D },
    neg = { D$TL[i] <- -1; D },
    mixed = { D$TL[i] <- c(D$TT[i[1]], D$TT[i[2]] * 1.5, NA); D })
}

rows <- lapply(seq_len(nrow(grid)), function(k) {
  g <- grid[k, ]
  D <- data.frame(TT = a$int_dead, DEAD = a$dead,
                  AGE = as.numeric(scale(a$age)))
  D$C3 <- as.numeric(seq_len(nrow(D)) %% g$every == 0 & D$DEAD == 0)
  D$TL <- ifelse(D$C3 > 0, D$TT * (1 - g$width), 0)
  D$W <- ifelse(seq_len(nrow(D)) %% 3 == 0, 2, 1)
  D <- degenerate_rows(D, g$degenerate)
  job <- paste("PROC HAZARD DATA=D; EVENT DEAD; TIME TT; ICENSOR C3 = TL;",
               if (g$weighted) "WEIGHT W;", parms[[g$model]])
  ix <- sprintf("X%d", k)
  haven::write_xpt(D, file.path(work, sprintf("hzr.J543.%s.dta", ix)),
                   version = 5, name = "HZRCALL")
  ctl <- file.path(work, sprintf("hzr.J543.%s.sas", ix))
  lst <- file.path(work, sprintf("hzr.J543.%s.lst", ix))
  writeLines(c(paste0("(   ", job, "   )"), sprintf("; OBSCOUNT %d ;", nrow(D)),
               "JOBID J543;", sprintf("JOBIX %s;", ix)), ctl)
  system(paste0("TMPDIR=", shQuote(work), " ", shQuote(bin), " < ",
                shQuote(ctl), " > ", shQuote(lst), " 2>&1"))
  out <- readLines(lst, warn = FALSE)
  # A one-parameter job is solved in closed form (hazrd2.c:70-74, NOOPTIM
  # via DCEOBJ), which prints "Log Likelihood" with a capital L.
  ll <- grep("^@9,Log [Ll]ikelihood = ", out)
  est <- function(nm) {
    h <- grep(paste0("^\\+3,", nm, " "), out)
    if (!length(ll) || !length(h)) return(NA_real_)
    as.numeric(sub("^\\+7,", "", out[h[length(h)] + 2L]))
  }
  data.frame(model = g$model, every = g$every, width = g$width,
             degenerate = g$degenerate, weighted = g$weighted,
             job = job, n_interval = sum(D$C3 > 0),
             loglik = if (length(ll) == 1L)
               as.numeric(sub("^;", "", out[ll + 1L])) else NA_real_,
             mue = est("MUE"), muc = est("MUC"),
             stringsAsFactors = FALSE)
})
tab <- do.call(rbind, rows)
version <- grep("C-Version", readLines(file.path(work, "hzr.J543.X1.lst")),
                value = TRUE)[[1L]]
dest <- "tests/testthat/fixtures/icensor-objective-oracle.csv"
writeLines(c(
  "# Generated by data-raw/icensor-objective-oracle.R; do not edit by hand.",
  paste0("# Binary: ", sub(path.expand("~"), "~", bin, fixed = TRUE), " (",
         trimws(sub("^\\$Note:", "", version)), ")"),
  utils::capture.output(utils::write.csv(tab, row.names = FALSE))), dest)
print(tab[, names(tab) != "job"])
