# Regenerate tests/testthat/fixtures/maxiter-zero-oracle.csv (#496).
#
# `MAXITER=0` sets PROC HAZARD's iteration limit to 0 (hazpprc.c:20-22), and
# a job with more than one free parameter then skips the optimizer and calls
# NOOPTIM() (hazrd2.c:71-74), which prints the log-likelihood at the starting
# values (hazrd2.c:133-145). Conservation of Events has already run by then
# (setcoe(), shape.c:52) unless NOCONSERVE is given (stmtprc.c:64, :123-127;
# the listing names the mode, cmpmeth.c:32-38). This grid records, per job,
# the mode the listing reports, the log-likelihood NOOPTIM() prints, and the
# early phase's MUE that the listing reports afterwards. Run from the package
# root:
#
#   Rscript data-raw/maxiter-zero-oracle.R [path/to/hazard]
#
# The data are the package's own `avc`, written as the XPORT file the binary
# reads from $TMPDIR/hzr.<JOBID>.<JOBIX>.dta (hazard.sas, opnfils.c), with
# three derived columns: C3 and TL, an interval-censored subset for ICENSOR
# (TL is also the entry time for LCENSOR), and W, a row weight.

args <- commandArgs(TRUE)
bin <- if (length(args)) args[[1L]] else
  path.expand("~/Documents/GitHub/hazard/dist/bin/hazard")
stopifnot(file.exists(bin), file.exists("data/avc.rda"))
work <- tempfile("maxiter-zero-oracle-")
dir.create(work)

env <- new.env()
load("data/avc.rda", envir = env)
a <- env$avc[stats::complete.cases(env$avc), ]
D <- data.frame(TT = a$int_dead, DEAD = a$dead,
                AGE = as.numeric(scale(a$age)))
D$C3 <- as.numeric(seq_len(nrow(D)) %% 5 == 0 & D$DEAD == 0)
D$TL <- ifelse(D$C3 > 0, D$TT * 0.5, 0)
D$W <- ifelse(seq_len(nrow(D)) %% 3 == 0, 2, 1)
n <- nrow(D)

B <- "EVENT DEAD; TIME TT;"
P1 <- "PARMS MUE=0.2 THALF=1; EARLY AGE;"
P2 <- "PARMS MUE=0.2 THALF=1 NU=1 MUC=0.01; EARLY AGE;"
job <- function(proc, rest) paste0("PROC HAZARD DATA=D MAXITER=0", proc, "; ", rest)
grid <- c(
  job("", paste(B, P1)),
  job(" NOCONSERVE", paste(B, P1)),
  job("", paste(B, P2)),
  job(" NOCONSERVE", paste(B, P2)),
  job(" CONSERVE", paste(B, P2)),
  job("", paste(B, "WEIGHT W;", P2)),
  job("", paste(B, "LCENSOR TL;", P2)),
  job("", paste(B, "ICENSOR C3 = TL;", P2)),
  job(" NOCONSERVE", paste(B, "ICENSOR C3 = TL;", P2)),
  # A value below 1 is truncated to 0 by the assignment to an int
  # (hazpprc.c:27, common.h:27).
  paste("PROC HAZARD DATA=D MAXITER=0.5;", B, P2),
  # A start MU far from the CoE value, and a late phase on this time scale:
  # shifts past a fixed search bracket (r-reviewer on #496).
  job("", paste(B, "PARMS MUE=0.000000000000001 THALF=1 NU=1 MUC=0.01; EARLY AGE;")),
  job("", paste(B, "PARMS MUE=0.000000000000001 THALF=1 NU=1; EARLY AGE;")),
  job("", paste(B, "PARMS MUE=0.2 THALF=1 NU=1 MUL=0.01 TAU=1 GAMMA=2 ALPHA=1 ETA=2; EARLY AGE;"))
)

rows <- lapply(seq_along(grid), function(k) {
  ix <- sprintf("X%d", k)
  haven::write_xpt(D, file.path(work, sprintf("hzr.J496.%s.dta", ix)),
                   version = 5, name = "HZRCALL")
  ctl <- file.path(work, sprintf("hzr.J496.%s.sas", ix))
  lst <- file.path(work, sprintf("hzr.J496.%s.lst", ix))
  writeLines(c(paste0("(   ", grid[[k]], "   )"),
               sprintf("; OBSCOUNT %d ;", n), "JOBID J496;",
               sprintf("JOBIX %s;", ix)), ctl)
  system(paste0("TMPDIR=", shQuote(work), " ", shQuote(bin), " < ",
                shQuote(ctl), " > ", shQuote(lst), " 2>&1"))
  out <- readLines(lst, warn = FALSE)
  # NOOPTIM() prints "Log Likelihood = " (capital L); the optimizer's own
  # summary prints "Log likelihood = ". Requiring the first, and the absence
  # of the second, is what shows that no optimization ran.
  ll <- grep("^@9,Log Likelihood = ", out)
  if (length(ll) != 1L || any(grepl("Log likelihood = ", out, fixed = TRUE))) {
    stop("row ", k, " is not a NOOPTIM() listing: ", grid[[k]])
  }
  coe <- grep("Conservation of events:", out, fixed = TRUE)
  mue <- grep("^\\+3,MUE", out)
  if (length(coe) != 1L || !length(mue)) {
    stop("row ", k, " lacks the CoE mode or the MUE estimate: ", grid[[k]])
  }
  mue <- mue[[length(mue)]]
  data.frame(job = grid[[k]],
             conserve = sub("^@31,", "", trimws(out[coe + 1L])),
             loglik = as.numeric(sub("^;", "", out[ll + 1L])),
             # Decimals as printed: the listing keeps about six significant
             # digits, so -1081.75 carries two and -295.609 three.
             loglik_decimals = nchar(sub("^[^.]*[.]?", "",
                                         trimws(sub("^;", "", out[ll + 1L])))),
             mue = as.numeric(sub("^\\+7,", "", out[mue + 2L])),
             stringsAsFactors = FALSE)
})
tab <- do.call(rbind, rows)
stopifnot(!anyNA(tab$loglik), !anyNA(tab$mue))
version <- grep("C-Version", readLines(file.path(work, "hzr.J496.X1.lst")),
                value = TRUE)[[1L]]
dest <- "tests/testthat/fixtures/maxiter-zero-oracle.csv"
writeLines(c(
  "# Generated by data-raw/maxiter-zero-oracle.R; do not edit by hand.",
  paste0("# Binary: ", sub(path.expand("~"), "~", bin, fixed = TRUE), " (",
         trimws(sub("^\\$Note:", "", version)), ")"),
  utils::capture.output(utils::write.csv(tab, row.names = FALSE))), dest)
print(tab)
