# Regenerate tests/testthat/fixtures/phase-name-oracle.csv (#440).
#
# Runs the HAZARD C binary on one EARLY statement per grid row and records
# whether PROC HAZARD runs the job and, if it does, which phase variables its
# listing reports. The binary is the oracle for what the translator's phase
# parser accepts. Run from the package root:
#
#   Rscript data-raw/phase-name-oracle.R [path/to/hazard]
#
# The binary reads its control file on stdin and its data from
# $TMPDIR/hzr.<JOBID>.<JOBIX>.dta, an XPORT file (hazard.sas, opnfils.c).

args <- commandArgs(TRUE)
bin <- if (length(args)) args[[1L]] else
  path.expand("~/Documents/GitHub/hazard/dist/bin/hazard")
stopifnot(file.exists(bin))
work <- tempfile("phase-oracle-")
dir.create(work)

grid <- c(
  "AGE", "AGE, _X1", "AGE, EARLY",
  "AGE, AGE*SEX", "AGE, AGE.", "AGE, A-B", "AGE, B SEX", "AGE, 1AGE",
  "AGE, AGE(1)", "AGE, LOG(X)", "AGE, F(X)=0.2", "AGE, LOG(P)",
  "AGE, LOG()", "AGE, LOG()=0.2", "AGE, LOG ( ) = 0.2", "AGE, LOG((",
  "AGE, LOG() /I", "AGE, LOG(), SEX", "LOG(X), AGE",
  "AGE*SEX, LOG()"
)

set.seed(440)
n <- 200
D <- data.frame(T = stats::rexp(n, 0.2), E = stats::rbinom(n, 1, 0.7),
                AGE = stats::rnorm(n), SEX = stats::rbinom(n, 1, 0.5),
                LOG = stats::rnorm(n), X = stats::rnorm(n), A = stats::rnorm(n),
                B = stats::rnorm(n), F = stats::rnorm(n),
                EARLY = stats::rnorm(n), `_X1` = stats::rnorm(n),
                check.names = FALSE)

# The phase-variable table: "@31,<Phase>:" opens a phase, "+1,<NAME>" is a
# variable, and the second "@31,-----" rule closes the table.
listed_vars <- function(lst) {
  start <- grep("^@31,Phase", lst)
  if (!length(start)) return(character(0))
  out <- character(0)
  phase <- NA_character_
  rules <- 0L
  for (l in lst[-seq_len(start[[1L]])]) {
    if (grepl("^@31,-{20,}", l)) {
      rules <- rules + 1L
      if (rules == 2L) break
    }
    if (grepl("^@31,[A-Za-z]+:", l)) phase <- sub("^@31,([A-Za-z]+):.*$", "\\1", l)
    if (grepl("^\\+1,[_A-Z][_A-Z0-9]*[[:space:]]*$", l)) {
      out <- c(out, paste0(phase, ":", trimws(sub("^\\+1,", "", l))))
    }
  }
  out
}

rows <- lapply(seq_along(grid), function(k) {
  ix <- sprintf("X%d", k)
  haven::write_xpt(D, file.path(work, sprintf("hzr.J440.%s.dta", ix)),
                   version = 5, name = "HZRCALL")
  ctl <- file.path(work, sprintf("hzr.J440.%s.sas", ix))
  lst <- file.path(work, sprintf("hzr.J440.%s.lst", ix))
  writeLines(c(paste0("(   PROC HAZARD DATA=D; EVENT E; TIME T;",
                      " PARMS MUE=0.2 THALF=1 NU=1 M=1 MUC=0.01;",
                      " EARLY ", grid[[k]], ";   )"),
               sprintf("; OBSCOUNT %d ;", n), "JOBID J440;",
               sprintf("JOBIX %s;", ix)), ctl)
  status <- system(paste0("TMPDIR=", shQuote(work), " ", shQuote(bin), " < ",
                          shQuote(ctl), " > ", shQuote(lst), " 2>&1"))
  out <- readLines(lst, warn = FALSE)
  syntax_exit <- any(grepl("EXITING DUE TO SYNTAX ERROR", out, fixed = TRUE))
  errors <- grep("^\\$ERROR:", out, value = TRUE)
  data.frame(
    early = grid[[k]],
    exit = status,
    # "rejected": SAS stops at parse. "runs": no syntax message at all.
    # "runs_after_reset": SAS printed a syntax error and ran anyway, because
    # `(` clears yysynerr (hazard_l.l:56).
    verdict = if (syntax_exit) "rejected" else if (length(errors))
      "runs_after_reset" else "runs",
    early_vars = if (syntax_exit) "" else
      paste(sub("^Early:", "", grep("^Early:", listed_vars(out), value = TRUE)),
            collapse = " "),
    first_error = if (length(errors)) errors[[1L]] else "",
    stringsAsFactors = FALSE
  )
})
tab <- do.call(rbind, rows)
version <- grep("C-Version", readLines(file.path(work, "hzr.J440.X1.lst")),
                value = TRUE)[[1L]]
dest <- "tests/testthat/fixtures/phase-name-oracle.csv"
writeLines(c(
  "# Generated by data-raw/phase-name-oracle.R; do not edit by hand.",
  paste0("# Binary: ", sub(path.expand("~"), "~", bin, fixed = TRUE), " (", trimws(sub("^\\$Note:", "", version)), ")"),
  paste0("# Binary file date: ", format(file.mtime(bin), "%Y-%m-%d")),
  paste0("# Source checkout when generated: ",
         system2("git", c("-C", dirname(dirname(dirname(bin))), "rev-parse",
                          "HEAD"), stdout = TRUE)),
  paste0("# Generated: ", format(Sys.Date()))
), dest)
suppressWarnings(utils::write.table(tab, dest, append = TRUE, sep = ",",
                                    row.names = FALSE, qmethod = "double"))
print(tab[, c("early", "verdict", "early_vars")], row.names = FALSE)
