# Regenerate tests/testthat/fixtures/proc-option-oracle.csv (#431).
#
# Runs the HAZARD C binary on one job per grid row and records whether PROC
# HAZARD runs it. The grid is the two shapes #431 names: a value on a PROC
# option that takes none, and a TIME/EVENT/RCENSOR/LCENSOR/WEIGHT statement
# with other than one operand, plus the forms of each that run. The binary is
# the oracle for the translator's verdict. Run from the package root:
#
#   Rscript data-raw/proc-option-oracle.R [path/to/hazard]
#
# The binary reads its control file on stdin and its data from
# $TMPDIR/hzr.<JOBID>.<JOBIX>.dta, an XPORT file (hazard.sas, opnfils.c).
# The verdict is read from the fatal-exit REASON the binary prints, never
# from one error string: SYNTAX or SEMANTIC is a refusal.

args <- commandArgs(TRUE)
bin <- if (length(args)) args[[1L]] else
  path.expand("~/Documents/GitHub/hazard/dist/bin/hazard")
stopifnot(file.exists(bin))
work <- tempfile("proc-option-oracle-")
dir.create(work)

P <- "PARMS MUE=0.2 THALF=0.3 NU=1 M=0;"
B <- "EVENT DEAD; TIME TT;"
grid <- c(
  # A value on each of the eleven bare options, and on one abbreviation.
  paste0("PROC HAZARD DATA=D ", c(
    "NOCOV=1", "CONSERVE=YES", "PRINTIT=1", "NOPRINT=0", "NOCOR=1",
    "NOCONSERVE=1", "QUASI=1", "STEEPEST=1", "NUMERIC=1", "NOLOG=1",
    "NONOTES=1", "P=1", "NOCOV =1", "NOCOV= 1", "NOCOV = 1", "NOCOV="),
    "; ", B, " ", P),
  # Other than one operand on a one-name statement.
  paste("PROC HAZARD DATA=D; EVENT DEAD EXTRA; TIME TT;", P),
  paste("PROC HAZARD DATA=D; EVENT DEAD; TIME TT EXTRA;", P),
  paste("PROC HAZARD DATA=D;", B, "WEIGHT EXTRA AGE;", P),
  paste("PROC HAZARD DATA=D;", B, "RCENSOR ZERO AGE;", P),
  paste("PROC HAZARD DATA=D;", B, "LCENSOR ZERO AGE;", P),
  paste("PROC HAZARD DATA=D; EVENT; TIME TT;", P),
  paste("PROC HAZARD DATA=D; EVENT DEAD; TIME;", P),
  paste("PROC HAZARD DATA=D;", B, "WEIGHT;", P),
  paste("PROC HAZARD DATA=D;", B, "RCENSOR;", P),
  paste("PROC HAZARD DATA=D;", B, "LCENSOR;", P),
  # Known negatives: the forms PROC HAZARD runs.
  paste("PROC HAZARD DATA=D NOCOV;", B, P),
  paste("PROC HAZARD DATA=D CONSERVE;", B, P),
  paste("PROC HAZARD DATA=D;", B, P),
  paste("PROC HAZARD DATA=D;", B, "WEIGHT ONE;", P),
  paste("PROC HAZARD DATA=D;", B, "RCENSOR ZERO;", P),
  paste("PROC HAZARD DATA=D;", B, "LCENSOR ZERO;", P),
  # A later `(` clears yysynerr (hazard_l.l:56), so PROC HAZARD runs these.
  paste("PROC HAZARD DATA=D; EVENT DEAD EXTRA; TIME TT;", P,
        "EARLY AGE, LOG();"),
  paste("PROC HAZARD DATA=D NOCOV=1;", B, P, "EARLY AGE, LOG();")
)

set.seed(431)
n <- 200
D <- data.frame(TT = stats::rexp(n, 0.2), DEAD = stats::rbinom(n, 1, 0.7),
                EXTRA = stats::rbinom(n, 1, 0.5), AGE = stats::rnorm(n),
                ZERO = 0, ONE = 1, LOG = stats::rnorm(n))

rows <- lapply(seq_along(grid), function(k) {
  ix <- sprintf("X%d", k)
  haven::write_xpt(D, file.path(work, sprintf("hzr.J431.%s.dta", ix)),
                   version = 5, name = "HZRCALL")
  ctl <- file.path(work, sprintf("hzr.J431.%s.sas", ix))
  lst <- file.path(work, sprintf("hzr.J431.%s.lst", ix))
  writeLines(c(paste0("(   ", grid[[k]], "   )"),
               sprintf("; OBSCOUNT %d ;", n), "JOBID J431;",
               sprintf("JOBIX %s;", ix)), ctl)
  status <- system(paste0("TMPDIR=", shQuote(work), " ", shQuote(bin), " < ",
                          shQuote(ctl), " > ", shQuote(lst), " 2>&1"))
  out <- readLines(lst, warn = FALSE)
  fatal <- regmatches(out, regexpr("fatal exit: [A-Z]+", out))
  reason <- if (length(fatal)) sub("fatal exit: ", "", fatal[[1L]]) else ""
  done <- any(grepl("Procedure HAZARD completed successfully", out,
                    fixed = TRUE))
  errors <- grep("^\\$ERROR:", out, value = TRUE)
  verdict <- if (reason %in% c("SYNTAX", "SEMANTIC")) "rejected" else
    if (!nzchar(reason) && done && length(errors)) "runs_after_reset" else
      if (!nzchar(reason) && done) "runs" else NA_character_
  # Anything else (a numerical fatal exit, a crash) says nothing about
  # whether PROC HAZARD accepts the job, so it cannot be an oracle row.
  if (is.na(verdict)) stop("row ", k, " has no verdict: ", grid[[k]])
  data.frame(job = grid[[k]], exit = status, reason = reason,
             verdict = verdict, stringsAsFactors = FALSE)
})
tab <- do.call(rbind, rows)
version <- grep("C-Version", readLines(file.path(work, "hzr.J431.X1.lst")),
                value = TRUE)[[1L]]
dest <- "tests/testthat/fixtures/proc-option-oracle.csv"
writeLines(c(
  "# Generated by data-raw/proc-option-oracle.R; do not edit by hand.",
  paste0("# Binary: ", sub(path.expand("~"), "~", bin, fixed = TRUE), " (",
         trimws(sub("^\\$Note:", "", version)), ")"),
  paste0("# Binary file date: ", format(file.mtime(bin), "%Y-%m-%d")),
  paste0("# Source checkout when generated: ",
         system2("git", c("-C", dirname(dirname(dirname(bin))), "rev-parse",
                          "HEAD"), stdout = TRUE)),
  paste0("# Generated: ", format(Sys.Date()))
), dest)
suppressWarnings(utils::write.table(tab, dest, append = TRUE, sep = ",",
                                    row.names = FALSE, qmethod = "double"))
print(tab[, c("job", "reason", "verdict")], row.names = FALSE)
