# Regenerate tests/testthat/fixtures/setg1-mzero-oracle.csv and
# tests/testthat/fixtures/setg1-mzero-data.csv (#471).
#
# What SETG1 does to an early phase that starts at M = 0 (setg1.c, pin
# dad7978), read off the HAZARD binary rather than the source:
#   M = 0, NU < 0 (:651-667) and M = 0, NU > 0 (:713-731): M is FIXED at 0,
#     unless NU is fixed and M free, when M is MOVED to 1 instead;
#   M = 0, NU = 0 with M fixed and NU free (:700-707): NU is MOVED to 1.
# The listing's "Initial Parameter Values" table prints the value each shape
# parameter is "Used" at and whether it is "Estimated?", after SETG1 and
# before any iteration, so it records the rewrite even when the fit then
# fails. Where the fit runs, the final log-likelihood and estimates are
# recorded too.
#
# Datasets:
#   "mzero"  300 rows drawn from the early phase itself at M = 0 (t_half 1,
#            nu 2, mu 2, censored at 20), so the M-fixed model has an interior
#            optimum. Drawn with hzr_decompos(), so this script loads the
#            package; the rows are written out (setg1-mzero-data.csv) and the
#            tests read them, never redraw them.
#   "ref"    avc (complete cases), as data-raw/setg1-oracle.R stages it;
#   "synth"  stream D's synthetic-n200-seed5, as data-raw/setg1-oracle.R.
# On ref and synth the M-fixed model has no interior optimum for these jobs:
# THALF runs off (to about 1e89 on synth, and past the overflow limit on avc,
# where the fit stops with DTRSFM1120, hzd_early_t2p.c:34-37). They are
# recorded for the outcome only.
#
# Run from the package root:  Rscript data-raw/setg1-mzero-oracle.R [hazard]

args <- commandArgs(TRUE)
bin <- if (length(args)) args[[1L]] else
  path.expand("~/Documents/GitHub/hazard/dist/bin/hazard")
stopifnot(file.exists(bin))
suppressMessages(pkgload::load_all(".", quiet = TRUE))
work <- tempfile("setg1-mzero-")
dir.create(work)

# --- mzero: drawn from the M = 0 early phase. Change NOTHING without the label.
MZERO_LABEL <- "mzero-n300-seed1 (t_half 1, nu 2, m 0, mu 2, censored at 20)"
set.seed(1)
n <- 300L
u <- -log(stats::runif(n)) / 2
g_cens <- hzr_decompos(20, 1, 2, 0)$G
tt <- vapply(u, function(target) {
  if (target >= g_cens) return(20)
  stats::uniroot(function(t) hzr_decompos(t, 1, 2, 0)$G - target,
                 c(1e-8, 20), tol = 1e-12)$root
}, numeric(1))
DM <- data.frame(TT = tt, DEAD = as.integer(u < g_cens))
data_dest <- "tests/testthat/fixtures/setg1-mzero-data.csv"
writeLines(c("# Generated by data-raw/setg1-mzero-oracle.R; do not edit by hand.",
             paste0("# Dataset: ", MZERO_LABEL)), data_dest)
suppressWarnings(utils::write.table(
  data.frame(TT = sprintf("%.17g", DM$TT), DEAD = DM$DEAD), data_dest,
  append = TRUE, sep = ",", row.names = FALSE, quote = FALSE))
# Read back what the tests will read, so SAS sees exactly those values.
DM <- utils::read.csv(data_dest, comment.char = "#")

load("data/avc.rda")
a <- avc[stats::complete.cases(avc), ]
D0 <- data.frame(TT = a$int_dead, DEAD = a$dead)
set.seed(5)
n <- 200L
D1 <- data.frame(TT = stats::rexp(n, 0.25) + 0.01,
                 DEAD = stats::rbinom(n, 1, 0.8),
                 AGE = as.numeric(scale(stats::rnorm(n))))[c("TT", "DEAD")]

grid <- c(
  mzero_nupos       = "MUE=1 THALF=0.5 M=0 NU=1",
  mzero_nuzero_fixm = "MUE=1 THALF=0.5 M=0 NU=0 FIXM",
  mzero_nupos_fixm  = "MUE=1 THALF=0.5 M=0 NU=1 FIXM",
  mzero_nuneg       = "MUE=1 THALF=0.5 M=0 NU=-1",
  mzero_nuneg_fixm  = "MUE=1 THALF=0.5 M=0 NU=-1 FIXM",
  mzero_nupos_fixnu = "MUE=1 THALF=0.5 M=0 NU=2 FIXNU",
  mzero_nuneg_fixnu = "MUE=1 THALF=0.5 M=0 NU=-1 FIXNU",
  mzero_both_fixed  = "MUE=1 THALF=0.5 M=0 NU=2 FIXM FIXNU",
  # M = 0 and NU = 0, which the rows above must not reach: both free moves
  # both to 1 (:686-691).
  mzero_nuzero_free = "MUE=1 THALF=0.5 M=0 NU=0",
  # #471's own three spellings, at #471's starting values.
  issue_nupos       = "MUE=0.2 THALF=1 M=0 NU=1",
  issue_nuzero_fixm = "MUE=0.2 THALF=1 M=0 NU=0 FIXM",
  issue_nupos_fixm  = "MUE=0.2 THALF=1 M=0 NU=1 FIXM",
  # Known negative: no M = 0, so SETG1 rewrites nothing.
  control_mone      = "MUE=1 THALF=0.5 M=1 NU=1"
)

run_one <- function(parms, ix, D) {
  haven::write_xpt(D, file.path(work, sprintf("hzr.J471.%s.dta", ix)),
                   version = 5, name = "HZRCALL")
  ctl <- file.path(work, sprintf("hzr.J471.%s.sas", ix))
  lst <- file.path(work, sprintf("hzr.J471.%s.lst", ix))
  writeLines(c(paste0("(   PROC HAZARD DATA=D; EVENT DEAD; TIME TT; PARMS ",
                      parms, ";   )"),
               sprintf("; OBSCOUNT %d ;", nrow(D)), "JOBID J471;",
               sprintf("JOBIX %s;", ix)), ctl)
  system(paste0("TMPDIR=", shQuote(work), " ", shQuote(bin), " < ",
                shQuote(ctl), " > ", shQuote(lst), " 2>&1"))
  readLines(lst, warn = FALSE)
}
num <- function(x) as.numeric(trimws(sub("^[;+@][0-9]*,?", "", x)))
# One parameter's row of the "Initial Parameter Values" table: the second
# number after the name is "Used", and the first Yes/No is "Estimated?".
initial <- function(out, name) {
  i0 <- grep("Initial Parameter Values", out, fixed = TRUE)[1L]
  i1 <- grep("Based on the values used", out, fixed = TRUE)[1L]
  stopifnot(!is.na(i0), !is.na(i1))
  s <- out[i0:i1]
  j <- which(s == paste0("+1,", name))[1L]
  stopifnot(!is.na(j))
  blk <- s[(j + 1L):min(length(s), j + 12L)]
  nums <- grep("^\\+[0-9]+, *-?[0-9.]+(E[-+][0-9]+)? *$", blk, value = TRUE)
  est <- grep(",(Yes|No) *$", blk, value = TRUE)[1L]
  c(used = num(nums[2L]), estimated = trimws(sub("^\\+[0-9]+,", "", est)))
}
final <- function(out) {
  i <- grep("Estimates for Model Parameters", out, fixed = TRUE)
  ll <- grep("Log likelihood", out, fixed = TRUE)
  if (!length(i) || !length(ll)) {
    return(c(ll = NA, thalf = NA, nu = NA, m = NA, mue = NA))
  }
  s <- out[i[length(i)]:length(out)]
  val <- function(pat) {
    j <- grep(pat, s)[1L]
    num(grep("^\\+7,", s[j:(j + 4L)], value = TRUE)[1L])
  }
  c(ll = num(out[ll[length(ll)] + 1L]), thalf = val("^@55,THALF"),
    nu = val("^@55,NU"), m = val("^@55,M *$"), mue = val("^ *\\+3,MUE"))
}
verdict <- function(out) {
  raised <- sub("^\\[hazard ERROR [^]]*\\] ", "",
                out[grepl("^\\[hazard ERROR", out)])
  code <- if (length(raised)) sub(" .*$", "", raised[[1L]]) else ""
  c(verdict = if (any(grepl("Estimates for Model Parameters", out,
                            fixed = TRUE)) && !nzchar(code)) "runs" else
    "no_result", code = code)
}

rows <- lapply(seq_along(grid), function(k) {
  om <- run_one(grid[[k]], sprintf("M%d", k), DM)
  o0 <- run_one(grid[[k]], sprintf("R%d", k), D0)
  o1 <- run_one(grid[[k]], sprintf("S%d", k), D1)
  nu <- initial(om, "NU")
  m <- initial(om, "M")
  vm <- verdict(om)
  fm <- final(om)
  data.frame(id = names(grid)[[k]], parms = grid[[k]],
             nu_used = as.numeric(nu[["used"]]), nu_estimated = nu[["estimated"]],
             m_used = as.numeric(m[["used"]]), m_estimated = m[["estimated"]],
             mzero = vm[["verdict"]], mzero_code = vm[["code"]],
             mzero_ll = fm[["ll"]], mzero_thalf = fm[["thalf"]],
             mzero_nu = fm[["nu"]], mzero_m = fm[["m"]], mzero_mue = fm[["mue"]],
             ref = verdict(o0)[["verdict"]], ref_code = verdict(o0)[["code"]],
             synth = verdict(o1)[["verdict"]], synth_code = verdict(o1)[["code"]],
             synth_ll = final(o1)[["ll"]], stringsAsFactors = FALSE)
})
tab <- do.call(rbind, rows)
version <- grep("C-Version", run_one(grid[[1L]], "V1", DM), value = TRUE)[[1L]]
dest <- "tests/testthat/fixtures/setg1-mzero-oracle.csv"
writeLines(c(
  "# Generated by data-raw/setg1-mzero-oracle.R; do not edit by hand.",
  paste0("# Binary: ", sub(path.expand("~"), "~", bin, fixed = TRUE), " (",
         trimws(sub("^\\$Note:", "", version)), ")"),
  paste0("# Binary file date: ", format(file.mtime(bin), "%Y-%m-%d")),
  paste0("# Source checkout when generated: ",
         system2("git", c("-C", dirname(dirname(dirname(bin))), "rev-parse",
                          "HEAD"), stdout = TRUE)),
  paste0("# Datasets: mzero = ", MZERO_LABEL,
         "; ref = avc (complete cases); synth = synthetic-n200-seed5"),
  paste0("# Generated: ", format(Sys.Date()))
), dest)
suppressWarnings(utils::write.table(tab, dest, append = TRUE, sep = ",",
                                    row.names = FALSE, qmethod = "double"))
print(tab, row.names = FALSE)

# --- The rewrite grid (#601): M x NU x FIX flags, on the mzero data. ---
# Every SETG1_mNuOne_FALSE() case with M in {-1, 0, 0.5} and NU in {-1, 0, 1},
# each with no flag, FIXM, FIXNU and both (the substitute review of #597). A
# job SETG1 refuses exits SEMANTIC and prints no "Initial Parameter Values"
# table, so its used/estimated columns are NA.
gg <- expand.grid(m = c(-1, 0, 0.5), nu = c(-1, 0, 1),
                  fl = c("", "FIXM", "FIXNU", "FIXM FIXNU"),
                  stringsAsFactors = FALSE)
grows <- lapply(seq_len(nrow(gg)), function(k) {
  parms <- trimws(sprintf("MUE=1 THALF=0.5 M=%g NU=%g %s", gg$m[k], gg$nu[k],
                          gg$fl[k]))
  out <- run_one(parms, sprintf("G%d", k), DM)
  has_table <- any(grepl("Initial Parameter Values", out, fixed = TRUE)) &&
    any(grepl("Based on the values used", out, fixed = TRUE))
  nu <- if (has_table) initial(out, "NU") else c(used = NA, estimated = NA)
  m <- if (has_table) initial(out, "M") else c(used = NA, estimated = NA)
  refused <- any(grepl("fatal exit: (SYNTAX|SEMANTIC)", out))
  v <- verdict(out)
  f <- final(out)
  data.frame(parms = parms, nu_used = as.numeric(nu[["used"]]),
             nu_estimated = nu[["estimated"]],
             m_used = as.numeric(m[["used"]]), m_estimated = m[["estimated"]],
             mzero = if (refused) "refused" else v[["verdict"]],
             mzero_code = v[["code"]], mzero_ll = f[["ll"]],
             mzero_thalf = f[["thalf"]], mzero_nu = f[["nu"]],
             mzero_m = f[["m"]], mzero_mue = f[["mue"]],
             stringsAsFactors = FALSE)
})
gtab <- do.call(rbind, grows)
stopifnot(nrow(gtab) == 36L, sum(gtab$mzero == "refused") >= 3L,
          all(is.na(gtab$m_used) == (gtab$mzero == "refused")))
gdest <- "tests/testthat/fixtures/setg1-rewrite-grid.csv"
writeLines(c(
  "# Generated by data-raw/setg1-mzero-oracle.R; do not edit by hand.",
  paste0("# Binary: ", sub(path.expand("~"), "~", bin, fixed = TRUE), " (",
         trimws(sub("^\\$Note:", "", version)), ")"),
  paste0("# Source checkout when generated: ",
         system2("git", c("-C", dirname(dirname(dirname(bin))), "rev-parse",
                          "HEAD"), stdout = TRUE)),
  paste0("# Dataset: mzero = ", MZERO_LABEL),
  paste0("# Generated: ", format(Sys.Date()))
), gdest)
suppressWarnings(utils::write.table(gtab, gdest, append = TRUE, sep = ",",
                                    row.names = FALSE, qmethod = "double"))
print(gtab[, 1:8], row.names = FALSE)
