# Regenerate tests/testthat/fixtures/setg1-oracle.csv (#424, #421 item 3).
#
# Runs the HAZARD C binary on one early-phase PARMS statement per grid row and
# records what it PRODUCES: "refused" (a fatal SYNTAX or SEMANTIC exit),
# "runs" (Normal exit and an "Estimates for Model Parameters" section) or
# "no_result" (anything else: no estimates, typically a domain error raised
# while fitting). The binary is the oracle for the class the translator must
# give each job. Run from the package root:
#
#   Rscript data-raw/setg1-oracle.R [path/to/hazard]
#
# The binary reads its control file on stdin and its data from
# $TMPDIR/hzr.<JOBID>.<JOBIX>.dta, an XPORT file, with OBSCOUNT set to the row
# count. Without the data file every job dies at "open input file", and the
# three classes cannot be told apart, so the first grid row is a known
# positive that must reach Normal exit.
#
# Each job is run on the package's `avc` data and again with its times
# multiplied by 10 and by 0.1; `stable` records whether all three runs gave
# the same class, so a data-dependent outcome is visible in the fixture.

args <- commandArgs(TRUE)
bin <- if (length(args)) args[[1L]] else
  path.expand("~/Documents/GitHub/hazard/dist/bin/hazard")
stopifnot(file.exists(bin))
work <- tempfile("setg1-oracle-")
dir.create(work)

grid <- c(
  known_positive = "MUE=0.2 THALF=1 NU=1 M=1",
  SETG1910_neg = "MUE=0.2 THALF=-1 FIXTHALF NU=1 M=1",
  SETG1910_zero = "MUE=0.2 THALF=0 FIXTHALF NU=1 M=1",
  thalf_neg_free = "MUE=0.2 THALF=-1 NU=1 M=1",
  thalf_zero_free = "MUE=0.2 THALF=0 NU=1 M=1",
  thalf_half_free = "MUE=0.2 THALF=-.5",
  SETG1940 = "MUE=0.2 THALF=1 M=-1 NU=-1 FIXM FIXNU",
  SETG1950 = "MUE=0.2 THALF=1 M=0 NU=0 FIXM FIXNU",
  SETG1960 = "MUE=0.2 THALF=1 M=1 NU=0 FIXM FIXNU",
  SETG1920 = "MUE=0.2 THALF=1 M=-1 NU=-1 FIXM FIXNU FIXMNU1",
  SETG1930 = "MUE=0.2 THALF=1 M=0 NU=0 FIXM FIXNU FIXMNU1",
  SETG1900 = "MUE=0.2 THALF=1 NU=1 M=1 DELTA=-2 FIXDELTA",
  SETG1901 = "MUE=0.2 THALF=1 NU=1 M=1 DELTA=2 FIXDELTA",
  mnu_zero_free = "MUE=0.2 THALF=1 M=0 NU=0",
  g1flag4_mpos = "MUE=0.2 THALF=1 M=1 NU=0",
  g1flag4_mpos_fixnu = "MUE=0.2 THALF=1 M=1 NU=0 FIXNU",
  g1flag4_mneg = "MUE=0.2 THALF=1 M=-1 NU=0",
  g1flag4_mneg_fixnu = "MUE=0.2 THALF=1 M=-1 NU=0 FIXNU",
  # g1flag 4 with M fixed: SETG1 reaches the same branch, but M does not move.
  g1flag4_mneg_both = "MUE=0.2 THALF=1 M=-1 NU=0 FIXM FIXNU",
  g1flag4_mzero_fixnu = "MUE=0.2 THALF=1 M=0 NU=0 FIXNU",
  # Known negatives: jobs PROC HAZARD runs.
  nu_zero_fixm = "MUE=0.2 THALF=1 M=1 NU=0 FIXM",
  thalf_fixed_pos = "MUE=0.2 THALF=0.5 FIXTHALF NU=1 M=1",
  mnu_both_fixed_pos = "MUE=0.2 THALF=1 NU=2 M=1 FIXM FIXNU",
  shape_defaults = "MUE=0.2"
)

load("data/avc.rda")
a <- avc[stats::complete.cases(avc), ]
D0 <- data.frame(TT = a$int_dead, DEAD = a$dead, EXTRA = a$mal,
                 AGE = as.numeric(scale(a$age)))

run_one <- function(parms, ix, D) {
  haven::write_xpt(D, file.path(work, sprintf("hzr.J424.%s.dta", ix)),
                   version = 5, name = "HZRCALL")
  ctl <- file.path(work, sprintf("hzr.J424.%s.sas", ix))
  lst <- file.path(work, sprintf("hzr.J424.%s.lst", ix))
  writeLines(c(paste0("(   PROC HAZARD DATA=D; EVENT DEAD; TIME TT; PARMS ",
                      parms, ";   )"),
               sprintf("; OBSCOUNT %d ;", nrow(D)), "JOBID J424;",
               sprintf("JOBIX %s;", ix)), ctl)
  system(paste0("TMPDIR=", shQuote(work), " ", shQuote(bin), " < ",
                shQuote(ctl), " > ", shQuote(lst), " 2>&1"))
  out <- readLines(lst, warn = FALSE)
  fatal <- regmatches(out, regexpr("fatal exit: [A-Z]+", out))
  reason <- sub("^\\[hazard ERROR [^]]*\\] ", "", out[grepl("^\\[hazard ERROR", out)])
  normal <- any(grepl("Normal exit", out, fixed = TRUE))
  est <- any(grepl("Estimates for Model Parameters", out, fixed = TRUE))
  list(
    class = if (any(grepl("SYNTAX|SEMANTIC", fatal))) "refused" else
      if (normal && est) "runs" else "no_result",
    reason = if (length(reason)) reason[[1L]] else if (normal) "Normal exit" else "",
    version = grep("C-Version", out, value = TRUE)
  )
}

rows <- lapply(seq_along(grid), function(k) {
  base <- run_one(grid[[k]], sprintf("X%d", k), D0)
  scaled <- vapply(c(10, 0.1), function(s) {
    D <- D0
    D$TT <- D$TT * s
    run_one(grid[[k]], sprintf("%s%d", if (s > 1) "A" else "B", k), D)$class
  }, character(1))
  data.frame(id = names(grid)[[k]], parms = grid[[k]], binary = base$class,
             reason = base$reason, stable = all(scaled == base$class),
             stringsAsFactors = FALSE)
})
tab <- do.call(rbind, rows)
stopifnot(tab$binary[[1L]] == "runs")   # the known positive reached Normal exit
version <- run_one(grid[[1L]], "V1", D0)$version[[1L]]
dest <- "tests/testthat/fixtures/setg1-oracle.csv"
writeLines(c(
  "# Generated by data-raw/setg1-oracle.R; do not edit by hand.",
  paste0("# Binary: ", sub(path.expand("~"), "~", bin, fixed = TRUE), " (",
         trimws(sub("^\\$Note:", "", version)), ")"),
  paste0("# Binary file date: ", format(file.mtime(bin), "%Y-%m-%d")),
  paste0("# Source checkout when generated: ",
         system2("git", c("-C", dirname(dirname(dirname(bin))), "rev-parse",
                          "HEAD"), stdout = TRUE)),
  "# Data: avc (complete cases); `stable` = same class with times x10 and x0.1",
  paste0("# Generated: ", format(Sys.Date()))
), dest)
suppressWarnings(utils::write.table(tab, dest, append = TRUE, sep = ",",
                                    row.names = FALSE, qmethod = "double"))
print(tab[, c("id", "binary", "stable", "reason")], row.names = FALSE)
